version: "3.9"
services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      pg_dsn: 'postgresql+asyncpg://alan:wakeupalan@postgres:5432/wake2'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "wake2"
      POSTGRES_USER: "alan"
      POSTGRES_PASSWORD: "wakeupalan"
    ports: #port forwarding
      - "5432:5432"
