version: "3.9"
services:
  web:
    container_name: app
    build: ./src
    command: bash -c './docker_entry_point.sh'
    environment:
      pg_dsn: 'postgresql+asyncpg://alan:wakeupalan@postgres:5432/wake2'
    depends_on:
      - postgres
    volumes:
      - ./src/:/usr/src/
    ports:
      - 8002:8000

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "wake2"
      POSTGRES_USER: "alan"
      POSTGRES_PASSWORD: "wakeupalan"
    ports: #port forwarding
      - "5432:5432"
