"""Added Events try 3

Revision ID: 4957a906b86b
Revises: a5367de6e4ea
Create Date: 2024-08-22 17:51:55.123140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4957a906b86b'
down_revision: Union[str, None] = 'a5367de6e4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('eventname', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_list_login'), 'event_list', ['login'], unique=True)
    op.create_index(op.f('ix_event_list_username'), 'event_list', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_list_username'), table_name='event_list')
    op.drop_index(op.f('ix_event_list_login'), table_name='event_list')
    op.drop_table('event_list')
    # ### end Alembic commands ###
