"""Event_date

Revision ID: 5428cd8fb078
Revises: 7fa612a71e5f
Create Date: 2024-08-28 18:35:02.280001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5428cd8fb078'
down_revision: Union[str, None] = '7fa612a71e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_list', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('event_list', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_event_list_login', table_name='event_list')
    op.drop_index('ix_event_list_username', table_name='event_list')
    op.create_foreign_key(None, 'event_list', 'user_list', ['user_id'], ['id'])
    op.drop_column('event_list', 'login')
    op.drop_column('event_list', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_list', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event_list', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_list', type_='foreignkey')
    op.create_index('ix_event_list_username', 'event_list', ['username'], unique=True)
    op.create_index('ix_event_list_login', 'event_list', ['login'], unique=True)
    op.alter_column('event_list', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('event_list', 'user_id')
    # ### end Alembic commands ###
